FROM ruby:2.4.1-alpine

LABEL maintainer="https://github.com/tootsuite/mastodon" \
      description="A GNU Social-compatible microblogging server"

ENV RAILS_ENV=production \
    NODE_ENV=production \
    SECRET_KEY_BASE=YOUR-SECRET-KEY-BASE

EXPOSE 4000

WORKDIR /mastodon

COPY Gemfile Gemfile.lock Rakefile package.json yarn.lock /mastodon/

RUN echo "@edge https://nl.alpinelinux.org/alpine/edge/main" >> /etc/apk/repositories \
 && BUILD_DEPS=" \
    postgresql-dev \
    libxml2-dev \
    libxslt-dev \
    build-base" \
 && apk -U upgrade && apk add \
    $BUILD_DEPS \
    nodejs@edge \
    nodejs-npm@edge \
    libpq \
    libxml2 \
    libxslt \
    ffmpeg \
    file \
    imagemagick@edge \
 && npm install -g npm@3 && npm install -g yarn \
 && bundle install --deployment --without test development \
 && yarn --ignore-optional \
 && yarn cache clean \
 && npm -g cache clean \
 && apk del $BUILD_DEPS \
 && rm -rf /tmp/* /var/cache/apk/*

COPY . /mastodon

RUN bundle exec rails assets:precompile

ENV RAILS_SERVE_STATIC_FILES 1

# Run it
ENTRYPOINT ["bin/start.sh"]
